name: DCSuperpick
version: ${project.version}
main: me.doragoncraft.dcsuperpick.DCSuperpick
api-version: 1.13
authors: [doragoncraft]
description: superpick insta break
commands:
  superpick:
    description: Toggle Superpick
    aliases: [sp, spick]
  superpickreload:
    description: Reload the Superpick config
    aliases: [spreload, spr]
permissions:
  dc.superpick.toggle:
    description: Give permission to toggle Superpick
    default: false
  dc.superpick.reload:
    description: Give permission to reload Superpick Config
    default: false
